// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAl-gakWjPkWE764i7j9DlEXy1abfOufE',
    androidClientId:
        '346265803262-dpa47ijsevjiv60mup2ba2epv849s6uv.apps.googleusercontent.com',
    appId: '1:346265803262:android:f2d8c01acbe422fd7b08af',
    messagingSenderId: '346265803262',
    projectId: 'shibuya-buddy-dev',
    storageBucket: 'shibuya-buddy-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAADyxmCZweM0U9yNQeFI6FxJ7OKJ8uD4w',
    iosClientId:
        '346265803262-e0lp7h85rep4cjareko3no2ir79g86u9.apps.googleusercontent.com',
    appId: '1:346265803262:ios:2bb6114de5aff3657b08af',
    messagingSenderId: '346265803262',
    projectId: 'shibuya-buddy-dev',
    storageBucket: 'shibuya-buddy-dev.firebasestorage.app',
    iosBundleId: 'com.shibuya.buddy.dev',
  );
}
