name: ios-deliver

on:
  release:
    types:
      - created

jobs:
  ios-deliver:
    runs-on: macos-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.3"
          cache: true

      - run: dart pub global activate flutterfire_cli

      - run: flutter pub get

      - run: chmod 755 ios/scripts/extract_dart_defines.sh

      - name: create prod.env file
        env:
          geminiAPIKey: ${{ secrets.GEMINI_API_KEY }}
          placeDetailAPIKey: ${{ secrets.PLACE_DETAIL_API_KEY }}
          revenueCatAppleAPIKey: ${{ secrets.REVENUE_CAT_APPLE_API_KEY }}
          revenueCatGoogleAPIKey: ${{ secrets.REVENUE_CAT_GOOGLE_API_KEY }}
          GoogleMapAPIKey: ${{ secrets.GOOGLE_MAP_API_KEY }}
          reversedClientId: ${{ secrets.REVERSED_CLIENT_ID }}
          admobiOSAppId: ${{ secrets.ADMOB_IOS_APP_ID }}
          admobAndroidAppId: ${{ secrets.ADMOB_ANDROID_APP_ID }}
          admobiOSBannerUnitId: ${{ secrets.ADMOB_IOS_BANNER_UNIT_ID }}
          admobAndroidBannerUnitId: ${{ secrets.ADMOB_ANDROID_BANNER_UNIT_ID }}
          admobiOSNativeUnitId: ${{ secrets.ADMOB_IOS_NATIVE_UNIT_ID }}
          admobAndroidNativeUnitId: ${{ secrets.ADMOB_ANDROID_NATIVE_UNIT_ID }}

        run: |
          mkdir -p ./dart_defines 
          touch ./dart_defines/prod.env
          echo "flavor=prod" > ./dart_defines/prod.env
          echo "appName=Shibuya Buddy" >> ./dart_defines/prod.env
          echo "appId=com.shibuya.buddy" >> ./dart_defines/prod.env
          echo "geminiAPIKey=$geminiAPIKey" >> ./dart_defines/prod.env
          echo "placeDetailAPIKey=$placeDetailAPIKey" >> ./dart_defines/prod.env
          echo "revenueCatAppleAPIKey=$revenueCatAppleAPIKey" >> ./dart_defines/prod.env
          echo "revenueCatGoogleAPIKey=$revenueCatGoogleAPIKey" >> ./dart_defines/prod.env
          echo "GoogleMapAPIKey=$GoogleMapAPIKey" >> ./dart_defines/prod.env
          echo "reversedClientId=$reversedClientId" >> ./dart_defines/prod.env
          echo "admobiOSAppId=$admobiOSAppId" >> ./dart_defines/prod.env
          echo "admobAndroidAppId=$admobAndroidAppId" >> ./dart_defines/prod.env
          echo "admobiOSBannerUnitId=$admobiOSBannerUnitId" >> ./dart_defines/prod.env
          echo "admobAndroidBannerUnitId=$admobAndroidBannerUnitId" >> ./dart_defines/prod.env
          echo "admobiOSNativeUnitId=$admobiOSNativeUnitId" >> ./dart_defines/prod.env
          echo "admobAndroidNativeUnitId=$admobAndroidNativeUnitId" >> ./dart_defines/prod.env
          cat ./dart_defines/prod.env

      - name: Import Prod Provisioning Profile
        run:
          | # 複数行の run を書きたい場合はこうする 以下、Provisioning Profilesを置くべきディレクトリにデコードしている
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/distribution.mobileprovision

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v3 # 外部パッケージを使っている
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Create Prod ipa file
        # GITHUB_RUN_NUMBER をビルドナンバーに指定することで被りがないようにしている。
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist --dart-define-from-file=dart_defines/prod.env --release

      - name: Upload to AppStoreConnect
        run: xcrun altool --upload-app -f "./build/ios/ipa/Shibuya Buddy.ipa" --type ios -u "${{ secrets.APPLE_ID }}" -p "${{ secrets.APPLE_APP_PASS }}"
