name: ios-deliver

on:
  pull_request:
    branches:
      - "releases/**"
    types: closed

jobs:
  ios-deliver:
    runs-on: macos-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.3"
          cache: true

      - run: flutter pub get

      - name: create prod.env file
        run: |
          mkdir -p ./dart_defines 
          touch ./dart_defines/prod.env
          echo "flavor=prod" > ./dart_defines/prod.env
          echo "appName=Shibuya Buddy" >> ./dart_defines/prod.env
          echo "appId=com.shibuya.buddy" >> ./dart_defines/prod.env
          cat ./dart_defines/prod.env

      - name: Import Prod Provisioning Profile
        run:
          | # 複数行の run を書きたい場合はこうする 以下、Provisioning Profilesを置くべきディレクトリにデコードしている
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/distribution.mobileprovision

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v3 # 外部パッケージを使っている
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
      
      - name: Create Prod ipa file
        # GITHUB_RUN_NUMBER をビルドナンバーに指定することで被りがないようにしている。
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist --dart-define-from-file=dart_defines/prod.env --release

      - name: Upload to AppStoreConnect
        run: xcrun altool --upload-app -f "./build/ios/ipa/shibuya-buddy.ipa" --type ios -u "${{ secrets.APPLE_ID }}" -p "${{ secrets.APPLE_APP_PASS }}"